// <auto-generated />
using Booky.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booky.DAL.Migrations
{
    [DbContext(typeof(BookyDbContext))]
    [Migration("20231225192530_SeedProduct1")]
    partial class SeedProduct1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Booky.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFic"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Booky.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrew Hunt, David Thomas",
                            CategoryId = 12,
                            Description = "A classic guide for software developers, offering practical advice on various aspects of programming and software development.",
                            ISBN = "978-0201616224",
                            ImageURL = "/images/ThePragmaticProgrammer.jfif",
                            ListPrice = 200.0,
                            Price = 200.0,
                            Price100 = 150.0,
                            Price50 = 180.0,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Stephen Hawking",
                            CategoryId = 2,
                            Description = "A bestselling exploration of the nature of the universe, explaining complex concepts in cosmology for a general audience.",
                            ISBN = "978-0553380163",
                            ImageURL = "/images/ABriefHistoryofTime.jfif",
                            ListPrice = 300.0,
                            Price = 300.0,
                            Price100 = 220.0,
                            Price50 = 250.0,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 3,
                            Author = "A.N. Kolmogorov, A.M. Yaglom",
                            CategoryId = 1,
                            Description = "A comprehensive overview of mathematics, providing insights into its content, methods, and broader significance.",
                            ISBN = "978-0486409160",
                            ImageURL = "/images/MathematicsItsContentMethodsandMeaning.jfif",
                            ListPrice = 100.0,
                            Price = 100.0,
                            Price100 = 50.0,
                            Price50 = 90.0,
                            Title = "Mathematics: Its Content, Methods and Meaning"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yuval Noah Harari",
                            CategoryId = 3,
                            Description = "An engaging exploration of the history of the human species, from ancient times to the present, offering a fresh perspective on our evolution.",
                            ISBN = "978-0062316097",
                            ImageURL = "/images/SapiensABriefHistoryofHumankind.jfif",
                            ListPrice = 400.0,
                            Price = 400.0,
                            Price100 = 360.0,
                            Price50 = 380.0,
                            Title = "Sapiens: A Brief History of Humankind"
                        });
                });

            modelBuilder.Entity("Booky.DAL.Models.Product", b =>
                {
                    b.HasOne("Booky.DAL.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
